### ISSUE TITLE
Unable to parse void return activity

### ISSUE THREAD

**Issue by mdsdimat** [spiral/temporal-bridge#39]
#### When I wait result of activity I get error: DataConverter is not set 

```
    #[ActivityMethod]
    public function ExcelToCSV(string $download, string $upload): void;
```

```
    #[WorkflowMethod]
    public function handle(string $download, string $upload)
    {
        yield $this->activity->ExcelToCSV($download, $upload);
    }
```

### Environment/Versions

- "spiral/temporal-bridge": "1.3.0"
- Docker temporalio/auto-setup:1.14.2

**Comment by butschster** [comment]
Did you add TemporalBootloader into your application?

**Comment by mdsdimat** [comment]
yes the activity works
Error on completion from activity

```
{
  "message": "DataConverter is not set",
  "source": "PHP_SDK",
  "stackTrace": "LogicException: DataConverter is not set in /var/www/vendor/temporal/sdk/src/DataConverter/EncodedValues.php:74\nStack trace:\n#0 /var/www/vendor/temporal/sdk/src/DataConverter/EncodedValues.php(169): Temporal\\DataConverter\\EncodedValues->getValue(0, Object(ReflectionNamedType))\n#1 /var/www/vendor/react/promise/src/FulfilledPromise.php(28): Temporal\\DataConverter\\EncodedValues::Temporal\\DataConverter\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#2 /var/www/vendor/react/promise/src/Promise.php(134): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL)\n#3 /var/www/vendor/react/promise/src/Promise.php(168): React\\Promise\\Promise::React\\Promise\\{closure}(Object(React\\Promise\\FulfilledPromise))\n#4 /var/www/vendor/react/promise/src/Promise.php(231): React\\Promise\\Promise->settle(Object(React\\Promise\\FulfilledPromise))\n#5 /var/www/vendor/react/promise/src/Deferred.php(36): React\\Promise\\Promise::React\\Promise\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#6 /var/www/vendor/temporal/sdk/src/Internal/Transport/CompletableResult.php(137): React\\Promise\\Deferred->resolve(Object(Temporal\\DataConverter\\EncodedValues))\n#7 /var/www/vendor/temporal/sdk/src/Internal/Events/EventEmitterTrait.php(47): Temporal\\Internal\\Transport\\CompletableResult->Temporal\\Internal\\Transport\\{closure}()\n#8 /var/www/vendor/temporal/sdk/src/WorkerFactory.php(278): Temporal\\WorkerFactory->emit('tick')\n#9 /var/www/vendor/temporal/sdk/src/WorkerFactory.php(393): Temporal\\WorkerFactory->tick()\n#10 /var/www/vendor/temporal/sdk/src/WorkerFactory.php(261): Temporal\\WorkerFactory->dispatch('\\n\\x03\\x08\\xA9F', Array)\n#11 /var/www/vendor/spiral/temporal-bridge/src/Dispatcher.php(63): Temporal\\WorkerFactory->run()\n#12 /var/www/vendor/spiral/framework/src/Core/src/ContainerScope.php(46): Spiral\\TemporalBridge\\Dispatcher->serve()\n#13 /var/www/vendor/spiral/framework/src/Core/src/Container.php(282): Spiral\\Core\\ContainerScope::runScope(Object(Spiral\\Core\\Container), Array)\n#14 /var/www/vendor/spiral/framework/src/Boot/src/AbstractKernel.php(212): Spiral\\Core\\Container->runScope(Array, Array)\n#15 /var/www/app.php(36): Spiral\\Boot\\AbstractKernel->serve()\n#16 {main}\n\nNext App\\Exception\\HttpException: DataConverter is not set in /var/www/app/src/Workflow/Normalizer/FileNormalizerWorkflow.php:66\nStack trace:\n#0 /var/www/vendor/temporal/sdk/src/Internal/Workflow/Process/Scope.php(356): App\\Workflow\\Normalizer\\FileNormalizerWorkflow->handle('https://s3.amaz...', 'https://s3.amaz...')\n#1 [internal function]: Temporal\\Internal\\Workflow\\Process\\Scope->call(Object(Closure), Object(Temporal\\DataConverter\\EncodedValues))\n#2 /var/www/vendor/temporal/sdk/src/Internal/Workflow/Process/Scope.php(516): Generator->throw(Object(LogicException))\n#3 /var/www/vendor/temporal/sdk/src/Internal/Events/EventEmitterTrait.php(47): Temporal\\Internal\\Workflow\\Process\\Scope->Temporal\\Internal\\Workflow\\Process\\{closure}()\n#4 /var/www/vendor/temporal/sdk/src/WorkerFactory.php(278): Temporal\\WorkerFactory->emit('tick')\n#5 /var/www/vendor/temporal/sdk/src/Internal/Workflow/Process/Scope.php(559): Temporal\\WorkerFactory->tick()\n#6 /var/www/vendor/temporal/sdk/src/Internal/Workflow/Process/Scope.php(523): Temporal\\Internal\\Workflow\\Process\\Scope->defer(Object(Closure))\n#7 /var/www/vendor/react/promise/src/RejectedPromise.php(28): Temporal\\Internal\\Workflow\\Process\\Scope->Temporal\\Internal\\Workflow\\Process\\{closure}(Object(LogicException))\n#8 /var/www/vendor/react/promise/src/Promise.php(134): React\\Promise\\RejectedPromise->then(Object(Closure), Object(Closure))\n#9 /var/www/vendor/react/promise/src/Promise.php(168): React\\Promise\\Promise::React\\Promise\\{closure}(Object(React\\Promise\\RejectedPromise))\n#10 /var/www/vendor/react/promise/src/Promise.php(148): React\\Promise\\Promise->settle(Object(React\\Promise\\RejectedPromise))\n#11 /var/www/vendor/react/promise/src/Promise.php(237): React\\Promise\\Promise->reject(Object(LogicException))\n#12 /var/www/vendor/react/promise/src/RejectedPromise.php(42): React\\Promise\\Promise::React\\Promise\\{closure}(Object(LogicException))\n#13 /var/www/vendor/react/promise/src/Promise.php(135): React\\Promise\\RejectedPromise->done(Object(Closure), Object(Closure), Object(Closure))\n#14 /var/www/vendor/react/promise/src/Promise.php(168): React\\Promise\\Promise::React\\Promise\\{closure}(Object(React\\Promise\\FulfilledPromise))\n#15 /var/www/vendor/react/promise/src/Promise.php(231): React\\Promise\\Promise->settle(Object(React\\Promise\\FulfilledPromise))\n#16 /var/www/vendor/react/promise/src/Deferred.php(36): React\\Promise\\Promise::React\\Promise\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#17 /var/www/vendor/temporal/sdk/src/Internal/Transport/CompletableResult.php(137): React\\Promise\\Deferred->resolve(Object(Temporal\\DataConverter\\EncodedValues))\n#18 /var/www/vendor/temporal/sdk/src/Internal/Events/EventEmitterTrait.php(47): Temporal\\Internal\\Transport\\CompletableResult->Temporal\\Internal\\Transport\\{closure}()\n#19 /var/www/vendor/temporal/sdk/src/WorkerFactory.php(278): Temporal\\WorkerFactory->emit('tick')\n#20 /var/www/vendor/temporal/sdk/src/WorkerFactory.php(393): Temporal\\WorkerFactory->tick()\n#21 /var/www/vendor/temporal/sdk/src/WorkerFactory.php(261): Temporal\\WorkerFactory->dispatch('\\n\\x03\\x08\\xA9F', Array)\n#22 /var/www/vendor/spiral/temporal-bridge/src/Dispatcher.php(63): Temporal\\WorkerFactory->run()\n#23 /var/www/vendor/spiral/framework/src/Core/src/ContainerScope.php(46): Spiral\\TemporalBridge\\Dispatcher->serve()\n#24 /var/www/vendor/spiral/framework/src/Core/src/Container.php(282): Spiral\\Core\\ContainerScope::runScope(Object(Spiral\\Core\\Container), Array)\n#25 /var/www/vendor/spiral/framework/src/Boot/src/AbstractKernel.php(212): Spiral\\Core\\Container->runScope(Array, Array)\n#26 /var/www/app.php(36): Spiral\\Boot\\AbstractKernel->serve()\n#27 {main}",
  "cause": {
    "message": "DataConverter is not set",
    "source": "PHP_SDK",
    "stackTrace": "LogicException: DataConverter is not set in /var/www/vendor/temporal/sdk/src/DataConverter/EncodedValues.php:74\nStack trace:\n#0 /var/www/vendor/temporal/sdk/src/DataConverter/EncodedValues.php(169): Temporal\\DataConverter\\EncodedValues->getValue(0, Object(ReflectionNamedType))\n#1 /var/www/vendor/react/promise/src/FulfilledPromise.php(28): Temporal\\DataConverter\\EncodedValues::Temporal\\DataConverter\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#2 /var/www/vendor/react/promise/src/Promise.php(134): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL)\n#3 /var/www/vendor/react/promise/src/Promise.php(168): React\\Promise\\Promise::React\\Promise\\{closure}(Object(React\\Promise\\FulfilledPromise))\n#4 /var/www/vendor/react/promise/src/Promise.php(231): React\\Promise\\Promise->settle(Object(React\\Promise\\FulfilledPromise))\n#5 /var/www/vendor/react/promise/src/Deferred.php(36): React\\Promise\\Promise::React\\Promise\\{closure}(Object(Temporal\\DataConverter\\EncodedValues))\n#6 /var/www/vendor/temporal/sdk/src/Internal/Transport/CompletableResult.php(137): React\\Promise\\Deferred->resolve(Object(Temporal\\DataConverter\\EncodedValues))\n#7 /var/www/vendor/temporal/sdk/src/Internal/Events/EventEmitterTrait.php(47): Temporal\\Internal\\Transport\\CompletableResult->Temporal\\Internal\\Transport\\{closure}()\n#8 /var/www/vendor/temporal/sdk/src/WorkerFactory.php(278): Temporal\\WorkerFactory->emit('tick')\n#9 /var/www/vendor/temporal/sdk/src/WorkerFactory.php(393): Temporal\\WorkerFactory->tick()\n#10 /var/www/vendor/temporal/sdk/src/WorkerFactory.php(261): Temporal\\WorkerFactory->dispatch('\\n\\x03\\x08\\xA9F', Array)\n#11 /var/www/vendor/spiral/temporal-bridge/src/Dispatcher.php(63): Temporal\\WorkerFactory->run()\n#12 /var/www/vendor/spiral/framework/src/Core/src/ContainerScope.php(46): Spiral\\TemporalBridge\\Dispatcher->serve()\n#13 /var/www/vendor/spiral/framework/src/Core/src/Container.php(282): Spiral\\Core\\ContainerScope::runScope(Object(Spiral\\Core\\Container), Array)\n#14 /var/www/vendor/spiral/framework/src/Boot/src/AbstractKernel.php(212): Spiral\\Core\\Container->runScope(Array, Array)\n#15 /var/www/app.php(36): Spiral\\Boot\\AbstractKernel->serve()\n#16 {main}",
    "cause": null,
    "applicationFailureInfo": {
      "type": "LogicException",
      "nonRetryable": false,
      "details": null
    },
    "failureInfo": "applicationFailureInfo"
  },
  "applicationFailureInfo": {
    "type": "App\\Exception\\HttpException",
    "nonRetryable": false,
    "details": null
  },
  "failureInfo": "applicationFailureInfo"
}```

**Comment by roxblnfk** [comment]
Closing the Issue as it pertains to the SDK (see https://github.com/temporalio/sdk-php/issues/498).
The issue may have already been fixed in https://github.com/temporalio/sdk-php/issues/442
